### ISSUE TITLE
Problemas al levantar la aplicación

### ISSUE THREAD

**Issue by npasserini** [proyectoarq1/productoscuidados#13]
Luego de levantar la aplicación siguiendo las instrucciones en README.md, e ingresar a http://localhost:9000/. Entiendo que falta configurar ${MONGOLAB_URI}, pero en las instrucciones no hay ninguna indicación al respecto.

Tampoco hay instrucciones sobre cómo instalar las herrmientas requeridas, yo lo hice según mi propio criterio que puede no ser adecuado. Mínimamente deberían indicar las versiones a utilizar. Luego me faltan instrucciones sobre qué testear específicamente.

La respuesta es:
![image](https://cloud.githubusercontent.com/assets/4633913/14716212/3875f896-07ec-11e6-8599-408277ebb83e.png)

En la consola aparece este error:

```
[error] application - 

! @6po6pk4ap - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[application.conf @ file:/home/nico/checkout/arq2/molinariRuizDiaz/target/scala-2.11/classes/application.conf: 37: Could not resolve substitution to a value: ${MONGOLAB_URI}]
    at play.api.Configuration$.configError(Configuration.scala:178) ~[play_2.11-2.4.6.jar:2.4.6]
    at play.api.Configuration$.load(Configuration.scala:103) ~[play_2.11-2.4.6.jar:2.4.6]
    at play.api.Configuration$.load(Configuration.scala:133) ~[play_2.11-2.4.6.jar:2.4.6]
    at play.api.ApplicationLoader$.createContext(ApplicationLoader.scala:91) ~[play_2.11-2.4.6.jar:2.4.6]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:151) ~[play-server_2.11-2.4.6.jar:2.4.6]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:150) ~[play-server_2.11-2.4.6.jar:2.4.6]
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.4.6.jar:2.4.6]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:150) ~[play-server_2.11-2.4.6.jar:2.4.6]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.6.jar:2.4.6]
    at scala.Option.map(Option.scala:146) ~[scala-library-2.11.8.jar:na]
Caused by: com.typesafe.config.ConfigException$UnresolvedSubstitution: application.conf @ file:/home/nico/checkout/arq2/molinariRuizDiaz/target/scala-2.11/classes/application.conf: 37: Could not resolve substitution to a value: ${MONGOLAB_URI}
    at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:108) ~[config-1.3.0.jar:na]
    at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179) ~[config-1.3.0.jar:na]
    at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142) ~[config-1.3.0.jar:na]
    at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379) ~[config-1.3.0.jar:na]
    at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312) ~[config-1.3.0.jar:na]
    at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398) ~[config-1.3.0.jar:na]
    at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179) ~[config-1.3.0.jar:na]
    at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142) ~[config-1.3.0.jar:na]
    at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379) ~[config-1.3.0.jar:na]
    at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312) ~[config-1.3.0.jar:na]

```

**Comment by ChristianDaniel** [comment]
Hola Nico. El error es porque esa variable la completa heroku con la URI de su base de mLab. En mi PC corrí la clase TestApp con el eclipse para probarlo sin levantar la aplicación, error mío porque debería funcionar de las 2 formas. De hecho si probás haciendole pedidos a la app de heroku eso funciona.
Si, tendríamos que poner qué pedidos se pueden hacer. Nosotros estuvimos usando Postman(addon de Chrome) para hacer lo pedidos get, post, etc. Pero como decís, tendríamos que ponerlo en la documentación. También los pasos para instalar las cosas. Y solucionar ese error para poder levantarlo localmente. Entendemos que heroku te genera un Procfile con algunos parámetros necesarios para correr la app, creemos que ese archivo sería necesario que lo creemos nosotros para tener así una referencia a la variable MONGOLAB_URI.

**Comment by npasserini** [comment]
Perfecto, vayan avisando a medida que vayan corrigiendo esas cosas así lo
vuelvo a probar.

2016-04-21 18:34 GMT+02:00 ChristianDaniel notifications@github.com:

**Comment by tatianamolinari** [comment]
Hola Nico,

Por lo pronto agregamos las versiones y los links de las mismas al
README.md y también las consultas que se le pueden hacer a la api.

Luego seguimos con el resto.

El 21 de abril de 2016, 18:29, Nico Passerini notifications@github.com
escribió:

> Perfecto, vayan avisando a medida que vayan corrigiendo esas cosas así lo
> vuelvo a probar.
> 
> 2016-04-21 18:34 GMT+02:00 ChristianDaniel notifications@github.com:
> 
> > Hola Nico. El error es porque esa variable la completa heroku con la URI
> > de su base de mLab. En mi PC corrí la clase TestApp con el eclipse para
> > probarlo sin levantar la aplicación, error mío porque debería funcionar
> > de
> > las 2 formas. De hecho si probás haciendole pedidos a la app de heroku
> > eso
> > funciona.
> > Si, tendríamos que poner qué pedidos se pueden hacer. Nosotros estuvimos
> > usando Postman(addon de Chrome) para hacer lo pedidos get, post, etc.
> > Pero
> > como decís, tendríamos que ponerlo en la documentación. También los pasos
> > para instalar las cosas. Y solucionar ese error para poder levantarlo
> > localmente. Entendemos que heroku te genera un Procfile con algunos
> > parámetros necesarios para correr la app, creemos que ese archivo sería
> > necesario que lo creemos nosotros para tener así una referencia a la
> > variable MONGOLAB_URI.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/proyectoarq1/productoscuidados/issues/13#issuecomment-213001998
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/proyectoarq1/productoscuidados/issues/13#issuecomment-213121108

## 

Saludos,

T_atiana._

**Comment by ChristianDaniel** [comment]
@npasserini , Solucionamos el problema de poder levantar la aplicación localmente(en heroku sigue funcionando), y agregamos más información en el Readme del repositorio.
Hicimos más pruebas sobre la API y tenemos un bug en la creación de foundprices. 
Además tenemos pendiente manejar errores en las peticiones para mostrar mensajes más descriptivos.
Saludos
