### ISSUE TITLE
Problemas para conectarse con la base de datos

### ISSUE THREAD

**Issue by npasserini** [proyectoarq1/productoscuidados#49]
Levante la app usando 

```
sh generate-docker-play.sh
sh run-docker-play.sh mongodbimage
```

Pero me da un error de conección. Tal vez el parámetro mongodbimage está mal, pero no tengo claro cuál es el valor correcto o cómo hacer para crear una imagen mongo adecuada.

El mensaje de error es el siguiente: 

```
play.api.UnexpectedException: Unexpected exception[MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=mongoplay:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketException: mongoplay}, caused by {java.net.UnknownHostException: mongoplay}}]]
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:151) [com.typesafe.play.play-netty-server_2.11-2.4.6.jar:2.4.6]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:148) [com.typesafe.play.play-netty-server_2.11-2.4.6.jar:2.4.6]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.util.Try$.apply(Try.scala:192) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.util.Failure.recover(Try.scala:216) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.8.jar:na]
    at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [com.typesafe.play.play-iteratees_2.11-2.4.6.jar:2.4.6]
    at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [com.typesafe.play.play-iteratees_2.11-2.4.6.jar:2.4.6]
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.11.8.jar:na]
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.8.jar:na]
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=mongoplay:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketException: mongoplay}, caused by {java.net.UnknownHostException: mongoplay}}]
    at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:369) ~[org.mongodb.mongo-java-driver-3.2.2.jar:na]
    at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:101) ~[org.mongodb.mongo-java-driver-3.2.2.jar:na]
    at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75) ~[org.mongodb.mongo-java-driver-3.2.2.jar:na]
    at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71) ~[org.mongodb.mongo-java-driver-3.2.2.jar:na]
    at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63) ~[org.mongodb.mongo-java-driver-3.2.2.jar:na]
    at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:210) ~[org.mongodb.mongo-java-driver-3.2.2.jar:na]
    at com.mongodb.operation.FindOperation.execute(FindOperation.java:482) ~[org.mongodb.mongo-java-driver-3.2.2.jar:na]
    at com.mongodb.operation.FindOperation.execute(FindOperation.java:79) ~[org.mongodb.mongo-java-driver-3.2.2.jar:na]
    at com.mongodb.Mongo.execute(Mongo.java:772) ~[org.mongodb.mongo-java-driver-3.2.2.jar:na]
    at com.mongodb.Mongo$2.execute(Mongo.java:759) ~[org.mongodb.mongo-java-driver-3.2.2.jar:na]
    at com.mongodb.DBCursor.initializeCursor(DBCursor.java:851) ~[org.mongodb.mongo-java-driver-3.2.2.jar:na]
    at com.mongodb.DBCursor.hasNext(DBCursor.java:152) ~[org.mongodb.mongo-java-driver-3.2.2.jar:na]
    at com.mongodb.casbah.MongoCursorBase$class.hasNext(MongoCursor.scala:73) ~[org.mongodb.casbah-core_2.11-3.1.1.jar:3.1.1]
    at com.mongodb.casbah.MongoCursor.hasNext(MongoCursor.scala:487) ~[org.mongodb.casbah-core_2.11-3.1.1.jar:3.1.1]
    at scala.collection.Iterator$class.foreach(Iterator.scala:893) ~[org.scala-lang.scala-library-2.11.8.jar:na]
    at com.mongodb.casbah.MongoCursor.foreach(MongoCursor.scala:487) ~[org.mongodb.casbah-core_2.11-3.1.1.jar:3.1.1]
    at backend.MongoAdapter.get_all_shops_mongo(MongoAdapter.scala:215) ~[play-scala-2-4.play-scala-2-4-1.0-SNAPSHOT-sans-externalized.jar:na]
    at controllers.ShopController$$anonfun$getShops$1.apply(ShopController.scala:24) ~[play-scala-2-4.play-scala-2-4-1.0-SNAPSHOT-sans-externalized.jar:na]
    at controllers.ShopController$$anonfun$getShops$1.apply(ShopController.scala:24) ~[play-scala-2-4.play-scala-2-4-1.0-SNAPSHOT-sans-externalized.jar:na]
    at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:439) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:439) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at scala.Option.map(Option.scala:146) ~[org.scala-lang.scala-library-2.11.8.jar:na]
    at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741) ~[com.typesafe.play.play-iteratees_2.11-2.4.6.jar:2.4.6]
    at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741) ~[com.typesafe.play.play-iteratees_2.11-2.4.6.jar:2.4.6]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.11.8.jar:na]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.11.8.jar:na]
    ... 6 common frames omitted


```

**Comment by ChristianDaniel** [comment]
Hola Nico, si es un error que se nos pasó y detectamos hoy.
El nombre de la imagen mongo que tenés en docker debe tener el mismo nombre
que el que tiene el application.docker.conf, osea actualmente "mongoplay"

2016-06-12 18:51 GMT-03:00 Nico Passerini notifications@github.com:
